### PR TITLE
add support for custom fixture filename per model

### PR DESCRIPTION
**Pull request by roupen**
Per issue #23 I added detection of fixture_filename method in models. I also added a test and updated the readme to illustrate the new feature. I noticed my editor removed trailing whitespace in some files let me know if you want me to undo that. I tried to match your coding and test style as close as I could. Thanks!

### CODE REVIEW

**Comment by jeremyevans** [comment]
This looks good, thanks for the patch! Could fix the whitespace issue and not modify the gemspec?  This is a new feature so the release would be 1.9.0 instead of 1.8.1.

**Comment by roupen** [comment]
Sorry for the delay I cleaned up the whitespace issue but I am not sure what you mean to not modify the gemspec? The only line I changed was to update the version which I switched to 1.9.0 as requested. Hope everything's ok let me know if you need me to change anything else!

**Comment by jeremyevans** [comment]
@roupen These changes look good.  I'll try to merge and test tomorrow.  Regarding the gemspec, it's a general rule that pull requests shouldn't modify it, because it is up to the maintainer when to make a release, not the pull requester.  In this case, I plan to release a new version, so it's not a big deal, but just keep that in mind for other pull requests.

**Comment by roupen** [comment]
ah I did not know that about the version, but it makes sense. I'll keep that in mind for the next pull request!

**Pull request merged**
